/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.logging.Logger;
import javax.swing.JOptionPane;

/** It describes the program and let choose a size for the table. Also a selection 
 * for the player side is allowed visually but -- in this version -- this selection does not have any effect.
 * You can play only with the fox.
 *
 * @author valyis
 */
public class guiSplashScreen extends javax.swing.JFrame {
    final static Logger logger = Logger.getLogger("FoxAndHounds");   
    EditingMethod editingMethod = null;
    javax.swing.JFrame frameEditing;

    /**
     * Creates new form guiReadSizeAndSide
     */
    public guiSplashScreen() {
        initComponents();
        //ButtonEditingFromScratch.setSelected(false);
        ButtonEditingFromStartTable.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        TextFieldTableSize = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ButtonStart = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ButtonEditingFromScratch = new javax.swing.JRadioButton();
        ButtonEditingFromStartTable = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Ebben a játékban a fox and hounds játékot valósítjuk meg.\\n  Előbb szerkesztjük a pályát, majd játszunk a megszerkesztett pályán véletlen ellenféllel szemben. ");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Adja be a pálya méretét (4--12, páros): ");
        jLabel1.setToolTipText("A pálya mérete egy 4 és 12 közötti páros  szám");

        TextFieldTableSize.setText("4");
        TextFieldTableSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTableSizeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Róka és kutyák");

        ButtonStart.setText("Induljon!");
        ButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStartActionPerformed(evt);
            }
        });

        jLabel4.setText("Hogyan történjen a páyaszerkesztés?");

        buttonGroup2.add(ButtonEditingFromScratch);
        ButtonEditingFromScratch.setSelected(true);
        ButtonEditingFromScratch.setText("üresből felpakolva");
        ButtonEditingFromScratch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditingFromScratchActionPerformed(evt);
            }
        });

        buttonGroup2.add(ButtonEditingFromStartTable);
        ButtonEditingFromStartTable.setText("kezdőállásból, lépegetve");
        ButtonEditingFromStartTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditingFromStartTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextFieldTableSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(ButtonStart))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonEditingFromStartTable)
                            .addComponent(ButtonEditingFromScratch))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(ButtonStart)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextFieldTableSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonEditingFromScratch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonEditingFromStartTable)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldTableSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTableSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTableSizeActionPerformed

    private void ButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStartActionPerformed
        int N = 0;
        while (N <= 3 || N>10 || N%2 !=0) {
            String s = TextFieldTableSize.getText().trim();
            try {
                N = Integer.parseInt(s);
            } catch (NumberFormatException nfe) {logger.warning("Nem szám az input méret");}
            if (N <= 3 || N>12 || N%2 !=0) {
                s = JOptionPane.showInputDialog(this, "Nem jó az input méret, mint szám. Legyen 4 és 10 közötti páros egész!");
                try { 
                    N = Integer.parseInt(s);
                }
                catch (NumberFormatException nfe2) {logger.warning("Nem jó az input méret, mint szám");}
                
            }
        }       
        if (ButtonEditingFromStartTable.isSelected()) editingMethod = EditingMethod.FROMSTARTINGTABLE; 
        else editingMethod = EditingMethod.FROMSCRATCH;
        frameEditing = new FrameEditing(editingMethod, N);
       frameEditing.setVisible(true);
       this.setEnabled(false);
       this.setVisible(false);
        
    }//GEN-LAST:event_ButtonStartActionPerformed

    private void ButtonEditingFromScratchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditingFromScratchActionPerformed
        ButtonEditingFromScratch.setSelected(true);
        //ButtonEditingFromStartTable.setSelected(false);        
    }//GEN-LAST:event_ButtonEditingFromScratchActionPerformed

    private void ButtonEditingFromStartTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditingFromStartTableActionPerformed
        //ButtonEditingFromScratch.setSelected(false);
        ButtonEditingFromStartTable.setSelected(true);        
    }//GEN-LAST:event_ButtonEditingFromStartTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiSplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ButtonEditingFromScratch;
    private javax.swing.JRadioButton ButtonEditingFromStartTable;
    private javax.swing.JButton ButtonStart;
    private javax.swing.JTextField TextFieldTableSize;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
